# ci.yaml
name: Pipeline-CI
on:
  push:
    branches: [ main ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # https://github.com/shivammathur/setup-php (community)
      - name: Setup PHP, extensions and composer with shivammathur/setup-php
        uses: shivammathur/setup-php@2.30.4
        with:
          extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
          
      # Cache artifacts like dependencies and build outputs to improve workflow execution time
      - name: Cache multiple paths
        uses: actions/cache@v4.0.2
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            vendor
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}
          
      - name: "Composer install"
        run: composer install --no-interaction --no-progress   
          
     # Install Symfony CLI
      - name: Symfony CLI
        run: |
          curl -sS https://get.symfony.com/cli/installer | bash
          mv ~/.symfony*/bin/symfony /usr/local/bin/symfony

      - name: Check Symfony version
        run: symfony -v
      
      # Check vulnerabilities
      - name: Symfony Check Vulnerabilities
        run: symfony check:security

        # PHP CS FIXER
      - name: PHP-CS-Fixer
        run: |
          composer require friendsofphp/php-cs-fixer
          ./vendor/bin/php-cs-fixer fix --dry-run

